      MODULE PROBLEM 
        IMPLICIT NONE
        CHARACTER(LEN=20) :: PROB 
        COMMON /PROBLEMNAME/ PROB
      END MODULE
      MODULE PERMUTE
        IMPLICIT NONE
        INTEGER(KIND=4) :: PERM(800)
        COMMON /PERMUTATION/ PERM
      END MODULE
      
      MODULE STATISTICS
        IMPLICIT NONE
        INTEGER(KIND=4), PARAMETER :: MAXDIM = 800
        INTEGER(KIND=4), PARAMETER :: MAXFUNEVL = 500000
        REAL(KIND=8) :: FOPT, FREC(MAXFUNEVL), FOPTREC(MAXFUNEVL)
        INTEGER(KIND=4) :: NF
        COMMON /STAT/ FOPT, FREC, FOPTREC, NF
      END MODULE 

