function createfigure(X1, Y1, X2)
%CREATEFIGURE(X1,Y1,X2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 06-Apr-2012 13:11:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 33.04]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim([-1 3]);
box('on');
hold('all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'Color',[0 0 1],...
    'DisplayName','NEWUOA');

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',2,'LineStyle','-.',...
    'DisplayName','NEWUOAs',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('log_2(\alpha)','FontSize',16);

% Create ylabel
ylabel('\pi_s(\alpha)','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthEast');

